// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "c6d4262d-4043-47d7-b974-0016bf9ef8df");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1555385534);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1555385654);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1555388487);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1555385294);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1555385174);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1555385414);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1555385894);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1555385774);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1555384862);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"37053\":1555385144655,\"37101\":1555385144655,\"37103\":1555385144655,\"37105\":1555389797075}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"790\":[1555385144663,1555388521305,1555389797278]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{fd33a56d-a6c6-4f59-ae1e-2218eadea7e3}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google,amazon");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1555308000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true},{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1555390304980");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1555392087980");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1555388476589");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1555392076589");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190327091201");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1555388521");
user_pref("browser.slowStartup.averageTime", 6854);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190327091201");
user_pref("browser.startup.homepage_override.mstone", "66.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 2);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1555384872123");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "80def383857d4ca69e2d43a9822ebe9f");
user_pref("extensions.blocklist.lastModified", "Fri, 12 Apr 2019 20:22:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1555385534);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190327091201");
user_pref("extensions.lastAppVersion", "66.0.2");
user_pref("extensions.lastPlatformVersion", "66.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"b857c644-f770-4c35-ac0d-9459bdf094c4\",\"screenshots@mozilla.org\":\"33a9c580-1459-45ef-acb5-b11640ed6dac\",\"webcompat-reporter@mozilla.org\":\"13799f72-26b5-45a3-8a5b-7c9cda31a88f\",\"webcompat@mozilla.org\":\"a33122c7-5e00-4343-8b6e-51e6155b3937\",\"fxmonitor@mozilla.org\":\"68d9928d-b581-4e64-89a8-c14ecf76e49c\"}");
user_pref("idle.lastDailyNotification", 1555385335);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1555385183);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190327091201");
user_pref("media.gmp-manager.lastCheck", 1555388458);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1555385336);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "a02c6a9b-1849-46ef-8590-598d072d8349");
user_pref("security.sandbox.plugin.tempDirSuffix", "fd967a5f-91c8-4c6a-94d2-9bfd36b82bf9");
user_pref("services.blocklist.addons.checked", 1555385180);
user_pref("services.blocklist.gfx.checked", 1555385180);
user_pref("services.blocklist.onecrl.checked", 1555385180);
user_pref("services.blocklist.pinning.checked", 1555385180);
user_pref("services.blocklist.plugins.checked", 1555385180);
user_pref("services.settings.clock_skew_seconds", -41);
user_pref("services.settings.last_update_seconds", 1555385454);
user_pref("services.settings.main.language-dictionaries.last_check", 1555385180);
user_pref("services.settings.main.onboarding.last_check", 1555385180);
user_pref("services.settings.main.sites-classification.last_check", 1555385180);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1555385335);
user_pref("toolkit.startup.last_success", 1555388519);
user_pref("toolkit.telemetry.cachedClientID", "6b007f63-509c-4399-93d4-cf64dc18155a");
user_pref("toolkit.telemetry.previousBuildID", "20190327091201");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
